// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRPVj3A48Ewdm3IhVIdPUX5SQpGBR65wI',
    appId: '1:641322782535:web:4effbd6296aeacd7ab4662',
    messagingSenderId: '641322782535',
    projectId: 'balanceapp-4bc73',
    authDomain: 'balanceapp-4bc73.firebaseapp.com',
    storageBucket: 'balanceapp-4bc73.firebasestorage.app',
    measurementId: 'G-GTENH68275',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhf8SlRB-usJyf4p4AM2c7cZBnS4x1Pp0',
    appId: '1:641322782535:android:0bbe0f7553190810ab4662',
    messagingSenderId: '641322782535',
    projectId: 'balanceapp-4bc73',
    storageBucket: 'balanceapp-4bc73.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyB34vz1onmxBUl8oRv4z8cBRtMh8kwyM',
    appId: '1:641322782535:ios:a60e2a2b426de948ab4662',
    messagingSenderId: '641322782535',
    projectId: 'balanceapp-4bc73',
    storageBucket: 'balanceapp-4bc73.firebasestorage.app',
    iosClientId: '641322782535-q2kko7irbrkkko08jg6sa971d9gr4vtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.balanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyB34vz1onmxBUl8oRv4z8cBRtMh8kwyM',
    appId: '1:641322782535:ios:a60e2a2b426de948ab4662',
    messagingSenderId: '641322782535',
    projectId: 'balanceapp-4bc73',
    storageBucket: 'balanceapp-4bc73.firebasestorage.app',
    iosClientId: '641322782535-q2kko7irbrkkko08jg6sa971d9gr4vtd.apps.googleusercontent.com',
    iosBundleId: 'com.example.balanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRPVj3A48Ewdm3IhVIdPUX5SQpGBR65wI',
    appId: '1:641322782535:web:e516f2526713d45cab4662',
    messagingSenderId: '641322782535',
    projectId: 'balanceapp-4bc73',
    authDomain: 'balanceapp-4bc73.firebaseapp.com',
    storageBucket: 'balanceapp-4bc73.firebasestorage.app',
    measurementId: 'G-QSFH67W71Q',
  );

}
